# DataSource Config
mongo-plus:
  data:
    mongodb:
      host: 127.0.0.1   #ip
      port: 27017   #端口
      database: email_security    #数据库名
      #      username: test    #用户名，没有可不填（若账号中出现@,!等等符号，不需要再进行转码！！！）
      #      password: test    #密码，同上（若密码中出现@,!等等符号，不需要再进行转码！！！）
      authenticationDatabase: admin     #验证数据库
      connectTimeoutMS: 50000   #在超时之前等待连接打开的最长时间（以毫秒为单位）
  configuration:
    field:
      camel-to-underline: true
    collection:
      mapping-strategy: camel_to_underline

common:
  llm:
    ai-chat-url: http://10.35.56.42:8223/v1/chat
    verify-email-url: http://10.35.56.41:8220/v1/eml_clf
  data:
    upload-path: /home/dwwangtianqi1/upload