server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /api

spring:
  application:
    name: email-security-demo
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

